name: Sales Scraper

on:
  schedule:
    # Runs at a random minute between 5 and 15, every 6 hours.
    - cron: '5-15/10 */6 * * *'
    # Runs daily at a random minute between 50 and 59 past 11 UTC.
    - cron: '50-59/5 11 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create Google credentials file
      run: |
        echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json

    - name: Create .env file
      run: |
        echo "GOOGLE_SHEET_ID=${{ secrets.GOOGLE_SHEET_ID }}" >> .env
        echo "PROXY_URL=${{ secrets.PROXY_URL }}" >> .env

    - name: Run scraper
      run: |
        python chatgptversionscraper_github.py

